[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html
    --alluredir=reports/allure-results
    --clean-alluredir

markers =
    smoke: Quick smoke tests
    regression: Full regression suite
    bvnk: BVNK API tests
    e2e: End-to-end tests
    functional: Functional tests
    frontend: Desktop web tests
    backend: Backend/API tests
    mobile: Mobile web tests
    mobile_app: Native mobile app tests
    android: Android specific tests
    ios: iOS specific tests
    slow: Slow running tests